CREATE TABLE tb_usuario_audit (
    id_usuario_audit NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario       NUMBER(5),
    email_usuario    VARCHAR2(100),
    data_hora        TIMESTAMP,
    operacao         VARCHAR2(10)
);

CREATE OR REPLACE TRIGGER audit_insert_usuario
AFTER INSERT ON tb_usuario
FOR EACH ROW
BEGIN
    INSERT INTO tb_usuario_audit (id_usuario, email_usuario, data_hora, operacao)
    VALUES (:NEW.id_usuario, :NEW.email_usuario, SYSTIMESTAMP, 'INSERT');
END;



CREATE OR REPLACE TRIGGER validar_cnpj_usuario
BEFORE INSERT OR UPDATE ON tb_usuario
FOR EACH ROW
DECLARE
    v_cnpj_invalido EXCEPTION;
BEGIN
    IF :NEW.cnpj_usuario IS NULL THEN
        RAISE v_cnpj_invalido;
    END IF;
EXCEPTION
    WHEN v_cnpj_invalido THEN
        RAISE_APPLICATION_ERROR(-20001, 'CNPJ do usuário não pode ser nulo.');
END;
